apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: wf-api
        envFrom:
        - configMapRef:
            name: wf-api-env
        - secretRef:
            name: wf-app-secrets
