namespace: writefluency

resources:
  - namespace.yaml
  - ../aspirate-output/wf-infra-postgres
  - ../aspirate-output/wf-infra-redis
  - ../aspirate-output/wf-infra-smtp
  - letsencrypt.yaml

patches:
  - path: wf-infra-postgres/statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: wf-infra-postgres
  - path: wf-infra-redis/statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: wf-infra-redis
  - path: wf-infra-smtp/deployment-patch.yaml
    target:
      kind: Deployment
      name: wf-infra-smtp
