---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-infra-redis
  labels:
    app: wf-infra-redis
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: wf-infra-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wf-infra-redis
    spec:
      containers:
      - name: wf-infra-redis
        image: redis:7.2-alpine
        imagePullPolicy: Always
        args:
        - --appendonly
        - yes
        ports:
        - name: redis
          containerPort: 6379
      terminationGracePeriodSeconds: 180