namespace: writefluency

resources:
- wf-infra-minio
- wf-propositions-minio-init
- wf-infra-postgres
- wf-infra-redis
- wf-infra-smtp
- wf-propositions-db-migrator
- wf-users-db-migrator
- wf-propositions-api
- wf-propositions-news-worker
- wf-users-api
- wf-webapp
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true


