---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-webapp
  labels:
    app: wf-webapp
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: wf-webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wf-webapp
    spec:
      containers:
      - name: wf-webapp
        image: docker.io/mateusmannes/wf-webapp:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4200
        envFrom:
        - configMapRef:
            name: wf-webapp-env
      terminationGracePeriodSeconds: 180