---
apiVersion: v1
kind: Service
metadata:
  name: wf-propositions-webapp
spec:
  type: ClusterIP
  selector:
    app: wf-propositions-webapp
  ports:
  - name: http
    port: 4200
    targetPort: 4200
