resources:
- statefulset.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: wf-minio-env
  literals:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=admin123

