---
apiVersion: v1
kind: Service
metadata:
  name: wf-minio
spec:
  type: ClusterIP
  selector:
    app: wf-minio
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
