/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { RegisterUserRequest } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/authentication/register
     * @param registerUserRequest 
     */
    apiAuthenticationRegisterPost(registerUserRequest: RegisterUserRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @endpoint post /api/authentication/token
     * @param loginRequest 
     */
    apiAuthenticationTokenPost(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<string>;

}
