/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ExerciseListItemDtoPagedResultDto } from '../model/models';
import { GetPropositionDto } from '../model/models';
import { Proposition } from '../model/models';
import { PropositionDto } from '../model/models';
import { TopicsDtoResult } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PropositionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/proposition/exercises
     * @param topic 
     * @param level 
     * @param pageNumber 
     * @param pageSize 
     * @param sortBy 
     */
    apiPropositionExercisesGet(topic?: string, level?: string, pageNumber?: number, pageSize?: number, sortBy?: string, extraHttpRequestParams?: any): Observable<ExerciseListItemDtoPagedResultDto>;

    /**
     * 
     * 
     * @endpoint post /api/proposition/generate-proposition
     * @param getPropositionDto 
     */
    apiPropositionGeneratePropositionPost(getPropositionDto: GetPropositionDto, extraHttpRequestParams?: any): Observable<PropositionDto>;

    /**
     * 
     * 
     * @endpoint get /api/proposition/{id}
     * @param id 
     */
    apiPropositionIdGet(id: number, extraHttpRequestParams?: any): Observable<Proposition>;

    /**
     * 
     * 
     * @endpoint post /api/proposition/{id}/regenerate
     * @param id 
     */
    apiPropositionIdRegeneratePost(id: number, extraHttpRequestParams?: any): Observable<Proposition>;

    /**
     * 
     * 
     * @endpoint get /api/proposition/topics
     */
    apiPropositionTopicsGet(extraHttpRequestParams?: any): Observable<TopicsDtoResult>;

}
