/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompareTextsDto } from '../model/models';
import { TextComparisonResult } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TextComparisonsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/text-comparison/compare-texts
     * @param compareTextsDto 
     */
    apiTextComparisonCompareTextsPost(compareTextsDto: CompareTextsDto, extraHttpRequestParams?: any): Observable<TextComparisonResult>;

}
