/**
 * WriteFluency.WebApi
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Proposition } from './proposition';

export interface BeginExerciseResultDto {
    access?: 'granted' | 'pro_required' | string;
    audioUrl?: string | null;
    audioExpiresAtUtc?: string | null;
    metadata?: Proposition;
}
export namespace BeginExerciseResultDto {
}
