/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplexityEnum } from './complexityEnum';


export interface Complexity { 
    id?: ComplexityEnum;
    description?: string | null;
}
export namespace Complexity {
}


