/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from './subjectEnum';
import { ComplexityEnum } from './complexityEnum';


export interface ExerciseListItemDto { 
    id?: number;
    title?: string | null;
    topic?: SubjectEnum;
    level?: ComplexityEnum;
    publishedOn?: string;
    imageFileId?: string | null;
    audioDurationSeconds?: number;
}
export namespace ExerciseListItemDto {
}


