/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from './subjectEnum';
import { ComplexityEnum } from './complexityEnum';


export interface GetPropositionDto { 
    complexity?: ComplexityEnum;
    subject?: SubjectEnum;
    alreadyGeneratedIds?: Array<number> | null;
}
export namespace GetPropositionDto {
}


