/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ISuccess { 
    readonly message?: string | null;
    readonly metadata?: { [key: string]: any | null; } | null;
}

