/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginRequest { 
    email?: string | null;
    password?: string | null;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
}

