/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NewsInfo { 
    id?: string | null;
    title?: string | null;
    description?: string | null;
    url?: string | null;
    imageUrl?: string | null;
    text?: string | null;
    textLength?: number;
}

