/**
 * WriteFluency.WebApi
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Proposition } from './proposition';

export interface PreviewExerciseAccessResultDto {
    accessStatus?: 'granted_free_window' | 'granted_pro' | 'preview_available_anonymous_sample' | 'preview_available_free_intro' | 'granted_catalog_teaser' | 'login_required_to_unlock_exercise' | 'upgrade_required_to_unlock_exercise' | string;
    audioUrl?: string | null;
    audioExpiresAtUtc?: string | null;
    metadata?: Proposition;
}
export namespace PreviewExerciseAccessResultDto {
}
