/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from './subjectEnum';
import { Proposition } from './proposition';
import { Subject } from './subject';
import { Complexity } from './complexity';
import { ComplexityEnum } from './complexityEnum';


export interface PropositionGenerationLog { 
    id?: number;
    generationDate?: string;
    subjectId?: SubjectEnum;
    complexityId?: ComplexityEnum;
    successCount?: number;
    success?: boolean;
    createdAt?: string;
    complexity?: Complexity;
    subject?: Subject;
    propositions?: Array<Proposition> | null;
}
export namespace PropositionGenerationLog {
}


