/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from './subjectEnum';
import { ComplexityEnum } from './complexityEnum';


export interface Proposition { 
    id?: number;
    publishedOn?: string;
    subjectId?: SubjectEnum;
    complexityId?: ComplexityEnum;
    audioDurationSeconds?: number;
    title?: string | null;
    imageFileId?: string | null;
    newsUrl?: string | null;
    requiresPro?: boolean;
}
export namespace Proposition {
}

