/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectEnum } from './subjectEnum';
import { NewsInfo } from './newsInfo';
import { PropositionGenerationLog } from './propositionGenerationLog';
import { Subject } from './subject';
import { Complexity } from './complexity';
import { ComplexityEnum } from './complexityEnum';


export interface Proposition { 
    id?: number;
    publishedOn?: string;
    subjectId?: SubjectEnum;
    complexityId?: ComplexityEnum;
    audioFileId?: string | null;
    voice?: string | null;
    audioDurationSeconds?: number;
    text?: string | null;
    textLength?: number;
    title?: string | null;
    imageFileId?: string | null;
    createdAt?: string;
    isDeleted?: boolean;
    deletedAt?: string | null;
    propositionGenerationLogId?: number | null;
    propositionGenerationLog?: PropositionGenerationLog;
    newsInfo?: NewsInfo;
    complexity?: Complexity;
    subject?: Subject;
}
export namespace Proposition {
}


