/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextComparison } from './textComparison';


export interface TextComparisonResult { 
    originalText?: string | null;
    userText?: string | null;
    comparisons?: Array<TextComparison> | null;
    accuracyPercentage?: number;
}

