/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextComparison } from './textComparison';
import { CorrectionTraceEntry } from './correctionTraceEntry';


export interface TextComparisonResult { 
    originalText?: string | null;
    userText?: string | null;
    comparisons?: Array<TextComparison> | null;
    accuracyPercentage?: number;
    correctionMode?: 'static' | 'normalized' | string | null;
    correctionTrace?: Array<CorrectionTraceEntry> | null;
    mistakePatternStatus?: 'generated' | 'login_required_to_unlock_review' | 'upgrade_required_to_unlock_review' | 'skipped_usage_limit' | 'skipped_disabled' | 'classifier_failed' | 'not_applicable' | string | null;
    mistakePatternMessage?: string | null;
    mistakePatternReviewSource?: 'none' | 'anonymous_sample' | 'free_intro' | 'free_monthly' | 'pro_paid' | string | null;
}
