/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextRange } from './textRange';


export interface TextComparison { 
    sourceComparisonIndex?: number;
    isDeterministicallyRefined?: boolean;
    isAiRefined?: boolean;
    originalTextRange?: TextRange;
    originalText?: string | null;
    userTextRange?: TextRange;
    userText?: string | null;
}
