/**
 * WriteFluency.WebApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ISuccess } from './iSuccess';
import { IError } from './iError';
import { IReason } from './iReason';
import { TopicsDto } from './topicsDto';


export interface TopicsDtoResult { 
    readonly isFailed?: boolean;
    readonly isSuccess?: boolean;
    readonly reasons?: Array<IReason> | null;
    readonly errors?: Array<IError> | null;
    readonly successes?: Array<ISuccess> | null;
    valueOrDefault?: TopicsDto;
    value?: TopicsDto;
}

