apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-users-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: wf-users-api
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: wf-users-api-env
        - secretRef:
            name: wf-users-secrets
