namespace: writefluency

resources:
  - ../aspirate-output/wf-propositions-api
  - ../aspirate-output/wf-propositions-db-migrator
  - ../aspirate-output/wf-propositions-news-worker
  - ../aspirate-output/wf-infra-minio
  - ../aspirate-output/wf-propositions-minio-init
  - ingress.yaml

images:
  - name: ghcr.io/mateus-mannes/wf-propositions-api
    newTag: replace_with_tag
  - name: ghcr.io/mateus-mannes/wf-propositions-news-worker
    newTag: replace_with_tag
  - name: ghcr.io/mateus-mannes/wf-propositions-db-migrator
    newTag: replace_with_tag
  - name: ghcr.io/mateus-mannes/wf-propositions-minio-init
    newTag: replace_with_tag

patches:
  - path: wf-api/deployment-patch.yaml
    target:
      kind: Deployment
      name: wf-propositions-api
  - path: wf-news-worker/deployment-patch.yaml
    target:
      kind: Deployment
      name: wf-propositions-news-worker
  - path: wf-db-migrator/deployment-patch.yaml
    target:
      kind: Deployment
      name: wf-propositions-db-migrator
  - path: wf-infra-minio/statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: wf-infra-minio
  - path: wf-propositions-minio-init/deployment-patch.yaml
    target:
      kind: Deployment
      name: wf-propositions-minio-init
